-- Seed GLOBAL tags for Baseball, Softball, Volleyball (offense/defense/plays),
-- matching the existing model. These sports map to the 3 buckets differently:
--   Baseball/Softball: offense = hitting & baserunning, defense = pitching &
--     fielding, plays = pitch types + small-ball situations.
--   Volleyball: offense = attacking/serving, defense = dig/block/receive,
--     plays = rally situations.
-- Periods (Q1-Q4 / 1H-2H) and star/POE are sport=null globals already present;
-- players category is per-team (roster). Idempotent (guarded per sport).

do $$
begin
  -- ── BASEBALL ─────────────────────────────────────────────────────────────────
  if not exists (select 1 from public.tags where scope='global' and sport='Baseball') then
    insert into public.tags (name, category, sort_order, scope, sport, tag_polarity) values
      ('Single','offense',1,'global','Baseball','positive'),
      ('Double','offense',2,'global','Baseball','positive'),
      ('Triple','offense',3,'global','Baseball','positive'),
      ('Home run','offense',4,'global','Baseball','positive'),
      ('RBI','offense',5,'global','Baseball','positive'),
      ('Walk (BB)','offense',6,'global','Baseball','positive'),
      ('Hit by pitch','offense',7,'global','Baseball','positive'),
      ('Sacrifice','offense',8,'global','Baseball','positive'),
      ('Stolen base','offense',9,'global','Baseball','positive'),
      ('Run scored','offense',10,'global','Baseball','positive'),
      ('Hard-hit ball','offense',11,'global','Baseball','positive'),
      ('Strikeout','offense',12,'global','Baseball','negative'),
      ('Groundout','offense',13,'global','Baseball','negative'),
      ('Flyout','offense',14,'global','Baseball','negative'),
      ('Popout','offense',15,'global','Baseball','negative'),
      ('Caught stealing','offense',16,'global','Baseball','negative'),
      ('Into double play','offense',17,'global','Baseball','negative'),
      ('Strikeout (pitcher)','defense',1,'global','Baseball','positive'),
      ('Groundout (fielded)','defense',2,'global','Baseball','positive'),
      ('Flyout (caught)','defense',3,'global','Baseball','positive'),
      ('Lineout','defense',4,'global','Baseball','positive'),
      ('Popout (caught)','defense',5,'global','Baseball','positive'),
      ('Double play turned','defense',6,'global','Baseball','positive'),
      ('Putout','defense',7,'global','Baseball','positive'),
      ('Fielding assist','defense',8,'global','Baseball','positive'),
      ('Diving catch','defense',9,'global','Baseball','positive'),
      ('Outfield assist (throw out)','defense',10,'global','Baseball','positive'),
      ('Pickoff','defense',11,'global','Baseball','positive'),
      ('Caught stealing (defense)','defense',12,'global','Baseball','positive'),
      ('Walk allowed','defense',13,'global','Baseball','negative'),
      ('Hit allowed','defense',14,'global','Baseball','negative'),
      ('Home run allowed','defense',15,'global','Baseball','negative'),
      ('Error','defense',16,'global','Baseball','negative'),
      ('Wild pitch / passed ball','defense',17,'global','Baseball','negative'),
      ('Fastball','plays',1,'global','Baseball','neutral'),
      ('Curveball','plays',2,'global','Baseball','neutral'),
      ('Changeup','plays',3,'global','Baseball','neutral'),
      ('Slider','plays',4,'global','Baseball','neutral'),
      ('Bunt','plays',5,'global','Baseball','neutral'),
      ('Hit and run','plays',6,'global','Baseball','neutral'),
      ('Steal attempt','plays',7,'global','Baseball','neutral'),
      ('Squeeze play','plays',8,'global','Baseball','neutral'),
      ('Full count','plays',9,'global','Baseball','neutral'),
      ('First-pitch swing','plays',10,'global','Baseball','neutral'),
      ('Rundown','plays',11,'global','Baseball','neutral'),
      ('Relay throw','plays',12,'global','Baseball','neutral'),
      ('Defensive shift','plays',13,'global','Baseball','neutral');
  end if;

  -- ── SOFTBALL (mirrors baseball + softball-specific slap / rise/drop pitches) ──
  if not exists (select 1 from public.tags where scope='global' and sport='Softball') then
    insert into public.tags (name, category, sort_order, scope, sport, tag_polarity) values
      ('Single','offense',1,'global','Softball','positive'),
      ('Double','offense',2,'global','Softball','positive'),
      ('Triple','offense',3,'global','Softball','positive'),
      ('Home run','offense',4,'global','Softball','positive'),
      ('Slap hit','offense',5,'global','Softball','positive'),
      ('RBI','offense',6,'global','Softball','positive'),
      ('Walk (BB)','offense',7,'global','Softball','positive'),
      ('Hit by pitch','offense',8,'global','Softball','positive'),
      ('Sacrifice','offense',9,'global','Softball','positive'),
      ('Stolen base','offense',10,'global','Softball','positive'),
      ('Run scored','offense',11,'global','Softball','positive'),
      ('Hard-hit ball','offense',12,'global','Softball','positive'),
      ('Strikeout','offense',13,'global','Softball','negative'),
      ('Groundout','offense',14,'global','Softball','negative'),
      ('Flyout','offense',15,'global','Softball','negative'),
      ('Popout','offense',16,'global','Softball','negative'),
      ('Caught stealing','offense',17,'global','Softball','negative'),
      ('Into double play','offense',18,'global','Softball','negative'),
      ('Strikeout (pitcher)','defense',1,'global','Softball','positive'),
      ('Groundout (fielded)','defense',2,'global','Softball','positive'),
      ('Flyout (caught)','defense',3,'global','Softball','positive'),
      ('Lineout','defense',4,'global','Softball','positive'),
      ('Popout (caught)','defense',5,'global','Softball','positive'),
      ('Double play turned','defense',6,'global','Softball','positive'),
      ('Putout','defense',7,'global','Softball','positive'),
      ('Fielding assist','defense',8,'global','Softball','positive'),
      ('Diving catch','defense',9,'global','Softball','positive'),
      ('Outfield assist (throw out)','defense',10,'global','Softball','positive'),
      ('Pickoff','defense',11,'global','Softball','positive'),
      ('Caught stealing (defense)','defense',12,'global','Softball','positive'),
      ('Walk allowed','defense',13,'global','Softball','negative'),
      ('Hit allowed','defense',14,'global','Softball','negative'),
      ('Home run allowed','defense',15,'global','Softball','negative'),
      ('Error','defense',16,'global','Softball','negative'),
      ('Wild pitch / passed ball','defense',17,'global','Softball','negative'),
      ('Fastball','plays',1,'global','Softball','neutral'),
      ('Changeup','plays',2,'global','Softball','neutral'),
      ('Rise ball','plays',3,'global','Softball','neutral'),
      ('Drop ball','plays',4,'global','Softball','neutral'),
      ('Screwball','plays',5,'global','Softball','neutral'),
      ('Curveball','plays',6,'global','Softball','neutral'),
      ('Bunt','plays',7,'global','Softball','neutral'),
      ('Slap','plays',8,'global','Softball','neutral'),
      ('Hit and run','plays',9,'global','Softball','neutral'),
      ('Steal attempt','plays',10,'global','Softball','neutral'),
      ('Squeeze play','plays',11,'global','Softball','neutral'),
      ('Full count','plays',12,'global','Softball','neutral'),
      ('Relay throw','plays',13,'global','Softball','neutral'),
      ('Defensive shift','plays',14,'global','Softball','neutral');
  end if;

  -- ── VOLLEYBALL ───────────────────────────────────────────────────────────────
  if not exists (select 1 from public.tags where scope='global' and sport='Volleyball') then
    insert into public.tags (name, category, sort_order, scope, sport, tag_polarity) values
      ('Kill','offense',1,'global','Volleyball','positive'),
      ('Ace','offense',2,'global','Volleyball','positive'),
      ('Assist (set)','offense',3,'global','Volleyball','positive'),
      ('Attack attempt','offense',4,'global','Volleyball','neutral'),
      ('Tip / roll shot','offense',5,'global','Volleyball','positive'),
      ('Back-row attack','offense',6,'global','Volleyball','positive'),
      ('Slide','offense',7,'global','Volleyball','positive'),
      ('Quick attack','offense',8,'global','Volleyball','positive'),
      ('Hitting error','offense',9,'global','Volleyball','negative'),
      ('Service error','offense',10,'global','Volleyball','negative'),
      ('Attack blocked','offense',11,'global','Volleyball','negative'),
      ('Ball-handling error','offense',12,'global','Volleyball','negative'),
      ('Dig','defense',1,'global','Volleyball','positive'),
      ('Block (solo)','defense',2,'global','Volleyball','positive'),
      ('Block assist','defense',3,'global','Volleyball','positive'),
      ('Block touch','defense',4,'global','Volleyball','positive'),
      ('Serve receive (pass)','defense',5,'global','Volleyball','positive'),
      ('Perfect pass','defense',6,'global','Volleyball','positive'),
      ('Save / pancake','defense',7,'global','Volleyball','positive'),
      ('Reception error','defense',8,'global','Volleyball','negative'),
      ('Missed dig','defense',9,'global','Volleyball','negative'),
      ('Net / blocking violation','defense',10,'global','Volleyball','negative'),
      ('Serve','plays',1,'global','Volleyball','neutral'),
      ('Free ball','plays',2,'global','Volleyball','neutral'),
      ('Transition','plays',3,'global','Volleyball','neutral'),
      ('In-system','plays',4,'global','Volleyball','neutral'),
      ('Out-of-system','plays',5,'global','Volleyball','neutral'),
      ('Overpass','plays',6,'global','Volleyball','neutral'),
      ('Down ball','plays',7,'global','Volleyball','neutral'),
      ('Joust','plays',8,'global','Volleyball','neutral'),
      ('Long rally','plays',9,'global','Volleyball','positive');
  end if;
end $$;
