-- =====================================================================
-- Universal (global) highlight tags for Flag Football and 7-on-7.
-- APPLIED LIVE via the Supabase MCP (migration: seed_flag_and_7on7_tags).
-- Mirrors the Basketball global set. `sport` matches teams.sport exactly
-- ('Flag Football' / '7-on-7') so they surface only for those teams via the
-- tagger's sport filter (global AND (sport is null OR sport = content sport)).
-- Coaches prune per-team via team_hidden_tags (see migration_team_hidden_tags.sql);
-- they can't hard-delete globals (super-admin/RLS). No stat_* — football stats
-- live in clip_football, not the tags stat layer.
-- =====================================================================
insert into public.tags (name, category, sport, scope, sort_order, team_id) values
-- ── Flag Football · Offense ──────────────────────────────────────────
('Touchdown','offense','Flag Football','global',0,null),
('Passing TD','offense','Flag Football','global',1,null),
('Rushing TD','offense','Flag Football','global',2,null),
('Completion','offense','Flag Football','global',3,null),
('Deep completion','offense','Flag Football','global',4,null),
('Big gain (20+)','offense','Flag Football','global',5,null),
('First down','offense','Flag Football','global',6,null),
('Slant','offense','Flag Football','global',7,null),
('Out','offense','Flag Football','global',8,null),
('Post','offense','Flag Football','global',9,null),
('Corner','offense','Flag Football','global',10,null),
('Go / Fly','offense','Flag Football','global',11,null),
('Hitch / Curl','offense','Flag Football','global',12,null),
('Wheel','offense','Flag Football','global',13,null),
('Crosser / Drag','offense','Flag Football','global',14,null),
('Screen','offense','Flag Football','global',15,null),
('Run / Rush','offense','Flag Football','global',16,null),
('QB scramble','offense','Flag Football','global',17,null),
('Handoff','offense','Flag Football','global',18,null),
('Reverse / Trick','offense','Flag Football','global',19,null),
('Play action','offense','Flag Football','global',20,null),
('Rollout','offense','Flag Football','global',21,null),
('2-pt conversion','offense','Flag Football','global',22,null),
('Drop','offense','Flag Football','global',23,null),
('Incompletion','offense','Flag Football','global',24,null),
('INT thrown','offense','Flag Football','global',25,null),
('Fumble','offense','Flag Football','global',26,null),
-- ── Flag Football · Defense ──────────────────────────────────────────
('Flag pull','defense','Flag Football','global',0,null),
('Sack','defense','Flag Football','global',1,null),
('TFL (behind LOS)','defense','Flag Football','global',2,null),
('Pass breakup','defense','Flag Football','global',3,null),
('Interception','defense','Flag Football','global',4,null),
('Forced fumble','defense','Flag Football','global',5,null),
('Fumble recovery','defense','Flag Football','global',6,null),
('QB pressure','defense','Flag Football','global',7,null),
('Missed flag pull','defense','Flag Football','global',8,null),
('Stop / turnover on downs','defense','Flag Football','global',9,null),
('Safety','defense','Flag Football','global',10,null),
-- ── Flag Football · Plays ────────────────────────────────────────────
('Trips','plays','Flag Football','global',0,null),
('Bunch','plays','Flag Football','global',1,null),
('Empty','plays','Flag Football','global',2,null),
('Spread','plays','Flag Football','global',3,null),
('Stack','plays','Flag Football','global',4,null),
('Motion','plays','Flag Football','global',5,null),
('Blitz','plays','Flag Football','global',6,null),
('Man coverage','plays','Flag Football','global',7,null),
('Zone coverage','plays','Flag Football','global',8,null),
('Cover 2','plays','Flag Football','global',9,null),
('Cover 3','plays','Flag Football','global',10,null),
-- ── 7-on-7 · Offense ─────────────────────────────────────────────────
('Touchdown','offense','7-on-7','global',0,null),
('Completion','offense','7-on-7','global',1,null),
('Deep completion','offense','7-on-7','global',2,null),
('First down','offense','7-on-7','global',3,null),
('Slant','offense','7-on-7','global',4,null),
('Out','offense','7-on-7','global',5,null),
('In / Dig','offense','7-on-7','global',6,null),
('Post','offense','7-on-7','global',7,null),
('Corner','offense','7-on-7','global',8,null),
('Go / Streak','offense','7-on-7','global',9,null),
('Hitch / Curl','offense','7-on-7','global',10,null),
('Comeback','offense','7-on-7','global',11,null),
('Wheel','offense','7-on-7','global',12,null),
('Seam','offense','7-on-7','global',13,null),
('Crosser / Drag','offense','7-on-7','global',14,null),
('Bubble / Screen','offense','7-on-7','global',15,null),
('Fade','offense','7-on-7','global',16,null),
('Back shoulder','offense','7-on-7','global',17,null),
('Scramble drill','offense','7-on-7','global',18,null),
('Contested catch','offense','7-on-7','global',19,null),
('2-pt conversion','offense','7-on-7','global',20,null),
('Drop','offense','7-on-7','global',21,null),
('Incompletion','offense','7-on-7','global',22,null),
('INT thrown','offense','7-on-7','global',23,null),
-- ── 7-on-7 · Defense ─────────────────────────────────────────────────
('Interception','defense','7-on-7','global',0,null),
('Pass breakup (PBU)','defense','7-on-7','global',1,null),
('Deflection','defense','7-on-7','global',2,null),
('Tipped ball','defense','7-on-7','global',3,null),
('Blanket coverage','defense','7-on-7','global',4,null),
('Forced incompletion','defense','7-on-7','global',5,null),
('Undercut / Jump','defense','7-on-7','global',6,null),
('Pressure','defense','7-on-7','global',7,null),
('Stop / turnover on downs','defense','7-on-7','global',8,null),
-- ── 7-on-7 · Plays ───────────────────────────────────────────────────
('Trips','plays','7-on-7','global',0,null),
('Bunch','plays','7-on-7','global',1,null),
('Empty','plays','7-on-7','global',2,null),
('Stack','plays','7-on-7','global',3,null),
('Motion','plays','7-on-7','global',4,null),
('Mesh','plays','7-on-7','global',5,null),
('Flood','plays','7-on-7','global',6,null),
('Smash','plays','7-on-7','global',7,null),
('Levels','plays','7-on-7','global',8,null),
('Four verticals','plays','7-on-7','global',9,null),
('Man','plays','7-on-7','global',10,null),
('Zone','plays','7-on-7','global',11,null),
('Cover 1','plays','7-on-7','global',12,null),
('Cover 2','plays','7-on-7','global',13,null),
('Cover 3','plays','7-on-7','global',14,null),
('Cover 4','plays','7-on-7','global',15,null),
('Blitz','plays','7-on-7','global',16,null);
-- =====================================================================
